### ISSUE TITLE
gauge init go  isn't working

### ISSUE THREAD

**Issue by Vad1mo** [getgauge-contrib/gauge-go#17]
I am trying to execute `gauge init go` however it fails with the error  `older must be a subfolder in GOPATH/src folder` however testgauge is a subfolder of `GOPATH/src`.

```sh
➜  testgauge> gauge init go  
Project folder must be a subfolder in GOPATH/src folder
Error ----------------------------------

Failed to initialize project. exit status 1

Get Support ----------------------------
	Docs:          https://docs.gauge.org
	Bugs:          https://github.com/getgauge/gauge/issues
	Chat:          https://gitter.im/getgauge/chat

Your Environment Information -----------
	darwin, 1.0.3
	go (0.1.2), java (0.6.9)

➜  testgauge> pwd
/Users/vadim/Development/golang/src/testgauge


➜  testgauge> go env       
..
GOPATH="/Users/vadim/development/golang"
```

**Comment by sriv** [comment]
small nitpick - the `GOPATH` and your `pwd` output are different, note `Development` v/s `development` in the paths.

With later version of golang, GOPATH is not mandatory and defaults to `$HOME/go`. So this should be handled in the runner.

However if GOPATH is set, then `gauge init go` works for me on linux, go 1.10.

**Comment by Vad1mo** [comment]
thx sir, resolved it now.
