### ISSUE TITLE
Able to debug gauge spec

### ISSUE THREAD

**Issue by thu2004** [getgauge-contrib/gauge-go#20]
Is it possible to add support for debugging gauge spec for golang ? How much effort will it take ? Any plan to implement it ?

**Comment by zabil** [comment]
There are no plans to support this at the moment. However it should be easy to add debug support on VS Code. Please reach out on the Gitter channel for support if you want to pick this up and send a pull request.

**Comment by apssouza22** [comment]
@zabil Considering that the other languages use remote debugging in order to debug specs, how would it be done with this runner?
Could you give some directions on how this would be done? I would be willing to open PR if changes are required

**Comment by sriv** [comment]
hi @apssouza22 

at a very high level, I think the best way would be to wire up [`delve`](https://github.com/go-delve/delve). From delve's [usage doc](https://github.com/go-delve/delve/blob/master/Documentation/usage/dlv.md) the executable needs to be launched by `dlv`. 

That should bring up a `dlv` server and any `dlv` client should then be able to attach itself. I see that `vscode-go` has support for debugging golang programs using `dlv`. That should be a good fit, given gauge supports `vscode` via an extension.

Hope this gives you some direction? Feel free to ask more, happy to help!

**Comment by apssouza22** [comment]
Support added here 
https://github.com/getgauge-contrib/gauge-go/pull/29
