### ISSUE TITLE
Failed to initialize project. Cannot find Gauge template 'go'

### ISSUE THREAD

**Issue by MariusSchmidt** [getgauge-contrib/gauge-go#34]
Installed gauge-go from source now, but 'gauge init go' fails with error "Failed to initialize project. Cannot find Gauge template 'go'"

```
gauge init go
Error ----------------------------------

[Gauge]
Failed to initialize project. Cannot find Gauge template 'go'

Get Support ----------------------------
	Docs:          https://docs.gauge.org
	Bugs:          https://github.com/getgauge/gauge/issues
	Chat:          https://github.com/getgauge/gauge/discussions

Your Environment Information -----------
	darwin, 1.4.3
	go (0.3.0), java (0.9.0)
```

**Comment by ferdypruis** [comment]
The required template was removed in a previous version. 

You could use my fork instead;
Run `gauge template go https://github.com/ferdypruis/gauge-template-go/archive/refs/tags/v1.0.0.zip` to install it.

Then `gauge init go` works as before.

**Comment by sriv** [comment]
Thanks for maintaining the go template @ferdypruis. 

Some context: Gauge made a change to remove the need for a central template repository (hence the `gauge template` command). As a result the templates were moved from gauge-repository to individual templates : https://github.com/getgauge?q=template

This allowed us to maintain them separately, enabling dependabot etc, but the bigger motivation is for the community to create and maintain their template of choice without the need for a gatekeeper.
