### ISSUE TITLE
Filter execution hooks by using tags are not compliant

### ISSUE THREAD

**Issue by vmatyusGitHub** [getgauge-contrib/gauge-go#35]
Filtering execution hook by tags handling in `gauge-go` differs from operations of [gauge-java](https://github.com/getgauge/gauge-java/releases), [gauge-js](https://github.com/getgauge/gauge-js/releases) and [gauge-python](https://github.com/getgauge/gauge-python/releases).

Also the [Gauge Doc](https://docs.gauge.org/execution.html?os=macos&language=javascript&ide=vscode#filter-specifications-and-scenarios-by-using-tags) has a specific chapter that describes this feature.

Based on these a I would say this is the expected operation:
* Suite hooks do not use tags
* Spec level tags, should have effect on `Spec`, `Scenario` and `Step` execution hooks
* Scenario level tags, should have effect on `Scenario` and `Step` execution hooks

To explain the first difference here is an example:
```
# Search Specification

Tags: search

## Successful search

* Search for product "Cup Cakes"
```

And let's have the following execution hook:
```go
var _ = gauge.beforeScenario(function () {
    print("Scenario Before Hook")
  }, []string{"search"}, testsuit.AND)`
```

### Actual operation

Currently, the spec level tags are not considered.
Will not execute the Scenario level hook with the spec level tag.

### Expected

Print out `Scenario Before Hook` before scenario execution.

The tag `search` should be accepted by `beforeScenario`, even if it is defined on `spec` level.

The second difference that I found is the Suite level should not use tags, it is only allowed in `gauge-go`.

**Comment by sriv** [comment]
Yes, tags are considered to be hierarchial. Thanks for raising this.

**Comment by vmatyusGitHub** [comment]
I've also created a possible solution suggestion: https://github.com/getgauge-contrib/gauge-go/pull/37 WDYT about it?
@sriv If you have a moment to review this work that would be greatly appreciated!

**Comment by vmatyusGitHub** [comment]
@sriv Thank you for your time and review!
Would you give me some estimation when this feature change will be available in a released version?

**Comment by sriv** [comment]
gauge-go 0.3.1 is out with this change. it will take upto 12 hours for the cache to refresh post which `gauge install go` should get you the latest release.

**Comment by vmatyusGitHub** [comment]
Thank you! 🙏
